In [4]:
from skimage import io
import matplotlib.pyplot as plt
from sklearn.decomposition import FastICA

In [5]:
ic = io.imread_collection('G:\Python_Learning\Python_RS\Image_Copy\Image\Landsat\*.tif')
images = []
shape1 = ic[0].shape

In [6]:
shape1

(998, 998)

In [7]:
for i in range(len(ic)):
    images.append(ic[i].flatten())

In [8]:
images

[array([-64, -71, -76, ..., 305, 185,  70]),
 array([386, 402, 378, ..., 703, 544, 452]),
 array([3311, 3527, 3537, ..., 2986, 2712, 2843]),
 array([163, 166, 150, ..., 685, 501, 342]),
 array([1695, 1710, 1712, ..., 1730, 1449, 1276]),
 array([ 844,  837,  830, ..., 1042,  836,  668])]

In [ ]:
ica = FastICA()
ica.fit(images)

In [11]:
print(ica.components_.shape)

(6, 996004)


In [13]:
ica.mean_

array([1055.83333333, 1095.16666667, 1088.5       , ..., 1241.83333333,
       1037.83333333,  941.83333333])

In [15]:
ica1 = ica.components_[0].reshape(shape1)
ica2 = ica.components_[1].reshape(shape1)
ica3 = ica.components_[2].reshape(shape1)
ica4 = ica.components_[3].reshape(shape1)
ica5 = ica.components_[4].reshape(shape1)
ica6 = ica.components_[5].reshape(shape1)

In [16]:
plt.imsave('G:/Python_Learning/Python_RS/Image_Copy/Image/Landsat/'+'ICA'+'.TIFF', ica1)

In [ ]:
fig , ax = plt.subplots(nrows=3 , ncols=2, figsize=(20,30))
ax[0,0].imshow(ica1, cmap='gray')
ax[0,0].set_title('ICA_1')
ax[0,0].axis('off')
ax[0,1].hist(ica1.ravel(), bins=256, density=True, histtype='bar', color='black')
ax[0,1].set_title('Histogram of ICA_1')
#########################
ax[1,0].imshow(ica2, cmap='gray')
ax[1,0].set_title('ICA_2')
ax[1,0].axis('off')
ax[1,1].hist(ica2.ravel(), bins=256, density=True, histtype='bar', color='black')
ax[1,1].set_title('Histogram of ICA-2')
##########################
ax[2,0].imshow(ica3, cmap='gray')
ax[2,0].set_title('ICA_3')
ax[2,0].axis('off')
ax[2,1].hist(ica3.ravel(), bins=256, density=True, histtype='bar', color='black')
ax[2,1].set_title('Histogram of ICA_3')
plt.show()